using System;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using Janus.Authentication.Mailboxes;
using Janus.Authentication.Oidc;
using Janus.Core;
using OpenIddict.Abstractions;
using OpenIddict.Server;
using OpenIddict.Server.AspNetCore;

namespace Janus.Hosting.Oidc;

/// <summary>
/// The token the library issues to the mail server's client for the signed-in person,
/// generated by the provider's own token generation so that it is the token the token
/// endpoint would issue that client, signed with the key the provider signs with now.
/// </summary>
/// <param name="factory">Where the provider's transaction comes from.</param>
/// <param name="dispatcher">What runs the provider's token generation.</param>
/// <param name="oidc">Where the session record the token stands on is read.</param>
/// <param name="clients">Where the mail server's client is looked up.</param>
/// <param name="client">
/// Which client the mail server is, or nothing where the deployment hosts no mailbox.
/// </param>
/// <param name="addresses">Where the provider is, which is the token's issuer.</param>
/// <param name="time">The clock the deployment runs on.</param>
/// <remarks>
/// Implements INT-MAIL-010, AUTH-OIDC-001 AC4, AUTH-OIDC-004, AUTH-OIDC-006 AC3 and
/// AUTH-KEY-001. The token carries the person the session is and nobody else, is issued
/// only from a session record that still answers, lasts no longer than an access token
/// may and no longer than the record, and leaves no row behind (INT-MAIL-010 AC1).
/// </remarks>
internal sealed class MailServerTokens(
    IOpenIddictServerFactory factory,
    IOpenIddictServerDispatcher dispatcher,
    OidcService oidc,
    IOidcClientStore clients,
    MailServerClient? client,
    AuthenticationAddresses addresses,
    TimeProvider time) : IMailServerTokens
{
    /// <inheritdoc/>
    public async ValueTask<Result<string>> IssueAsync(
        SubjectId subject,
        SessionId session,
        CancellationToken cancellationToken)
    {
        Error? failure = null;

        MintedSession minted = (await oidc.MintAsync(session, cancellationToken).ConfigureAwait(false))
            .Match(record => record, error => Withheld(error, ref failure));

        if (failure is not null)
        {
            return Result.Failure<string>(failure);
        }

        // AUTH-OIDC-001 AC4: the token is the signed-in person's, so a session that is
        // someone else's issues nothing.
        if (minted.Subject != subject)
        {
            return Result.Failure<string>(Error.From(ErrorCodes.Denied));
        }

        // LIB-HOST-001: a deployment that registers a mail server declares its client or
        // does not start, and bootstrap registers that client where the integration is
        // enabled; a registry without it is a deployment put together wrongly.
        if (client is null
            || await clients.FindAsync(client.ClientId, cancellationToken).ConfigureAwait(false)
                is not { Kind: OidcClientKind.Protocol } registered)
        {
            throw new InvalidOperationException("The mail server's client is not registered as a protocol client.");
        }

        DateTimeOffset now = time.GetUtcNow();
        TimeSpan lifetime = minted.AccessTokenLifetime < minted.Remaining
            ? minted.AccessTokenLifetime
            : minted.Remaining;

        OpenIddictServerTransaction transaction = await factory.CreateTransactionAsync().ConfigureAwait(false);

        transaction.CancellationToken = cancellationToken;

        var generating = new OpenIddictServerEvents.GenerateTokenContext(transaction)
        {
            ClientId = registered.ClientId,
            CreateTokenEntry = false,
            IsReferenceToken = false,
            PersistTokenPayload = false,
            Principal = Principal(subject, registered, now, lifetime),
            TokenFormat = OpenIddictConstants.TokenFormats.Private.JsonWebToken,
            TokenType = OpenIddictConstants.TokenTypeIdentifiers.AccessToken,
        };

        await dispatcher.DispatchAsync(generating).ConfigureAwait(false);

        return generating.IsRejected || string.IsNullOrEmpty(generating.Token)
            ? throw new InvalidOperationException("The provider generated no token for the mail server's client.")
            : Result.Success(generating.Token);
    }

    private static MintedSession Withheld(Error error, ref Error? failure)
    {
        failure = error;

        return default!;
    }

    // What the provider's own preparation of an access-token principal gives a token
    // for this client: the subject, the client as presenter, as client_id and as the
    // audience the mail server's adapter verifies (AUTH-OIDC-006 AC3), and the scopes it
    // was registered with.
    private ClaimsPrincipal Principal(
        SubjectId subject,
        OidcClient registered,
        DateTimeOffset now,
        TimeSpan lifetime)
    {
        var identity = new ClaimsIdentity(
            OpenIddictServerAspNetCoreDefaults.AuthenticationScheme,
            OpenIddictConstants.Claims.Name,
            OpenIddictConstants.Claims.Role);

        identity.AddClaim(new Claim(OpenIddictConstants.Claims.Subject, subject.ToString()));

        var principal = new ClaimsPrincipal(identity);

        _ = principal
            .SetPresenters(registered.ClientId)
            .SetAudiences(registered.ClientId)
            .SetScopes(registered.Scopes)
            .SetClaim(OpenIddictConstants.Claims.ClientId, registered.ClientId)
            .SetClaim(OpenIddictConstants.Claims.Private.Issuer, new Uri(addresses.Provider, UriKind.Absolute).AbsoluteUri)
            .SetCreationDate(now)
            .SetExpirationDate(now + lifetime);

        return principal;
    }
}
