using System;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Janus.Authentication;
using Janus.Authentication.BreakGlass;
using Janus.Authentication.Sessions;
using Janus.Authorization.Grants;
using Janus.Authorization.Roles;
using Janus.Core;
using Janus.Core.Configuration;
using Janus.Hosting.Bff;
using Microsoft.AspNetCore.Http;
using Xunit;

namespace Janus.Hosting.Tests.BreakGlass;

/// <summary>
/// The sealed emergency credential over <c>POST /auth/break-glass</c> and
/// <c>POST /admin/break-glass/generate</c> of chapter 09 section 8: generated by a
/// stepped-up system administrator or from the session it opens, spent by its one use,
/// and loud every time (OPS-BOOT-002, OPS-BOOT-004, AUTH-STEP-004, FE-BG-001).
/// </summary>
[Trait("kind", "unit")]
public sealed class BreakGlassEndpointTests : IAsyncDisposable
{
    private const string Owner = "owner@example.test";

    private const string OwnerNumber = "+441632960099";

    private const string Operator = "ops@example.test";

    private const string OperatorNumber = "+441632960098";

    private const string Present = "/auth/break-glass";

    private const string Generate = "/admin/break-glass/generate";

    private static readonly OrganizationId Administration =
        new(Guid.Parse("33333333-3333-4333-8333-333333333333"));

    private static readonly RoleName SystemAdministrator = RoleName.Parse("system-administrator");

    private static readonly string[] Rota = ["rota@example.test"];

    private static readonly Guid Holder = Guid.Parse("55555555-5555-4555-8555-555555555555");

    private readonly Deployment _deployment = new();
    private readonly RandomNumberGenerator _randomness = RandomNumberGenerator.Create();
    private readonly SubjectId _emergency;

    /// <summary>
    /// A deployment administered by one organization, whose reserved account holds the
    /// system administrator's permissions there, and whose owner has routine alerts
    /// turned off.
    /// </summary>
    public BreakGlassEndpointTests()
    {
        Flow.Prepare(_deployment);
        _deployment.Administers(Administration);

        _deployment.Configuration.Set(Settings.AlertingEmailDestinations, [Operator]);
        _deployment.Configuration.Set(Settings.AlertingSmsDestinations, [OperatorNumber]);
        _deployment.Configuration.Set(Settings.AlertingOwnerEmail, Owner);
        _deployment.Configuration.Set(Settings.AlertingOwnerSms, OwnerNumber);
        _deployment.Configuration.Set(Settings.AlertingOwnerEnabled, false);

        _emergency = SubjectId.New(_randomness);
        _deployment.Reserves(_emergency);
        _deployment.Accounts.Stands(_emergency, AccountState.Active);

        foreach (Permission permission in Permissions.All)
        {
            _deployment.Gate.Grant(_emergency, Administration, permission);
        }
    }

    /// <inheritdoc/>
    public async ValueTask DisposeAsync()
    {
        _randomness.Dispose();
        await _deployment.DisposeAsync();
    }

    /// <summary>
    /// OPS-BOOT-002 AC1: use opens a session for the reserved account and spends the
    /// credential, so the second attempt is refused as consumed, and a code that was
    /// never issued is refused as invalid.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC1_UseConsumesTheCredentialAsync()
    {
        string credential = await GeneratedAsync();

        Answer opened = await PresentedAsync(new Browser(_deployment), credential);
        Answer again = await PresentedAsync(new Browser(_deployment), credential);
        Answer unknown = await PresentedAsync(new Browser(_deployment), Drawn());

        Assert.Equal(StatusCodes.Status200OK, opened.Status);
        Assert.Contains(opened.SetCookie, cookie => cookie.StartsWith(BrowserCookies.Session + "=", StringComparison.Ordinal));
        Assert.Equal(_emergency, Assert.Single(_deployment.BreakGlassAudit.Used).Emergency);
        Assert.Equal(StatusCodes.Status409Conflict, again.Status);
        Assert.Equal(ErrorCodes.BreakGlassConsumed.ToString(), again.Text("code"));
        Assert.Equal(StatusCodes.Status422UnprocessableEntity, unknown.Status);
        Assert.Equal(ErrorCodes.BreakGlassInvalid.ToString(), unknown.Text("code"));
        Assert.NotNull(Assert.Single(_deployment.BreakGlass.Issues).ConsumedAt);
    }

    /// <summary>
    /// OPS-BOOT-002 AC2 and AUTH-STEP-004 AC3: the session ends at the configured
    /// lifetime however recently it was used, and the exception ends with it.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC2_TheSessionExpiresAtTheConfiguredLifetimeAsync()
    {
        _deployment.Configuration.Set(Settings.BreakGlassSessionLifetime, TimeSpan.FromHours(2));

        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);

        Assert.Equal(StatusCodes.Status200OK, (await PresentedAsync(owner, credential)).Status);

        Session opened = _deployment.Sessions.All.Single(session => session.Subject == _emergency);

        Assert.True(opened.SatisfiesEveryGate);
        Assert.Equal(_deployment.Clock.GetUtcNow().AddHours(2), opened.AbsoluteExpiry);

        _deployment.Clock.Advance(TimeSpan.FromMinutes(119));

        Answer live = await owner.SendAsync("GET", "/auth/session");

        _deployment.Clock.Advance(TimeSpan.FromMinutes(2));

        Answer ended = await owner.SendAsync("GET", "/auth/session");

        Assert.Equal(StatusCodes.Status200OK, live.Status);
        Assert.Equal(StatusCodes.Status401Unauthorized, ended.Status);
    }

    /// <summary>
    /// OPS-BOOT-002 AC3: use is raised at once on every channel, to the operator and
    /// to the owner, with the owner's routine alerts turned off.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC3_UseReachesTheOwnerWithOwnerAlertsOffAsync()
    {
        string credential = await GeneratedAsync();

        _ = await _deployment.CarryAlertsAsync();
        _deployment.Mail.Taken.Clear();
        _deployment.Sms.Taken.Clear();

        Assert.Equal(StatusCodes.Status200OK, (await PresentedAsync(new Browser(_deployment), credential)).Status);
        Assert.Equal(1, await _deployment.CarryAlertsAsync());
        Assert.Equal(
            [Operator, Owner],
            _deployment.Mail.Taken.Select(mail => mail.Destination.Value).Order(StringComparer.Ordinal));
        Assert.Equal(
            [OperatorNumber, OwnerNumber],
            _deployment.Sms.Taken.Select(message => message.Destination.Value).Order(StringComparer.Ordinal));
        Assert.Equal("used", Raised().Details["event"].GetString());
    }

    /// <summary>
    /// OPS-BOOT-002 AC4, AUTH-STEP-004 AC1 and AC2: the session grants system
    /// administration with no further step-up, and the grant records the reserved
    /// account as who granted it.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC4_TheSessionGrantsSystemAdministrationAsync()
    {
        await _deployment.Roles.CreateAsync(Role.Of(SystemAdministrator, Permissions.All), CancellationToken.None);

        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        _deployment.Clock.Advance(TimeSpan.FromHours(1));

        Answer granted = await owner.SendAsync(
            "POST",
            "/admin/grants",
            ("subjectType", "user"),
            ("subjectId", Holder),
            ("resourceType", "organization"),
            ("resourceId", Administration.ToString()),
            ("role", SystemAdministrator.ToString()),
            ("reason", "The operator is unreachable."));

        Assert.Equal(StatusCodes.Status201Created, granted.Status);

        Grant grant = (await _deployment.AccessGrants.FindAsync(
            new GrantId(Guid.Parse(granted.Text("id"))),
            CancellationToken.None))!;

        Assert.Equal(SystemAdministrator, grant.Role);
        Assert.Equal(_emergency, grant.GrantedBy);
    }

    /// <summary>
    /// OPS-BOOT-002 AC4 and AUTH-RECOV-002a: the session approves the recovery of the
    /// one system administrator there is, with no further step-up.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC4_TheSessionApprovesARecoveryAsync()
    {
        string credential = await GeneratedAsync();
        SubjectId administrator = _deployment.Directory.Created[^1].Subject;
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        _deployment.Clock.Advance(TimeSpan.FromHours(1));

        Answer approved = await owner.SendAsync(
            "POST",
            "/admin/recovery/approve",
            ("subject", administrator.ToString()),
            ("reason", "The administrator lost every factor."),
            ("channelUsed", Flow.Address));

        Assert.Equal(StatusCodes.Status200OK, approved.Status);
    }

    /// <summary>
    /// AUTH-STEP-004 AC1 and AC2: the session changes the alert destinations with no
    /// further step-up, and the change is written down as the reserved account's, which
    /// no session but a break-glass one acts as.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task AUTH_STEP_004_AC2_AnActionInTheSessionIsAuditedAsTheReservedAccountAsync()
    {
        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        Answer changed = await owner.SendAsync(
            "PUT",
            "/admin/config/alerting.email.destinations",
            ("value", Rota),
            ("reason", "The operator is unreachable."));

        Assert.Equal(StatusCodes.Status204NoContent, changed.Status);
        Assert.Equal(_emergency, Assert.Single(_deployment.Changes.Written).Actor);
    }

    /// <summary>
    /// OPS-BOOT-002 AC6 and FE-BG-001 AC1: the session is an auth session, so another
    /// application opens from it with no further credential.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_AC6_AnApplicationOpensFromTheSessionAsync()
    {
        const string page = "/account/profile";

        await _deployment.Clients.RecordAsync(
            new OidcClient(
                "this-application",
                "this-application",
                OidcClientKind.BrowserApplication,
                "https://identity.example.test/auth/signon/return",
                ["openid"]),
            OpaqueToken.Of("a-secret-the-deployment-set").Fingerprint(),
            DateTimeOffset.MinValue,
            TestContext.Current.CancellationToken);

        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);
        var application = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        Answer forwarded = await application.SendAsync("GET", "/auth/signon?returnTo=" + Uri.EscapeDataString(page));
        Answer issued = await owner.SendAsync("GET", Local(forwarded.Location));
        Answer established = await application.SendAsync("GET", Local(issued.Location));

        Assert.Equal(StatusCodes.Status302Found, established.Status);
        Assert.Equal(page, established.Location);
        Assert.Equal(StatusCodes.Status200OK, (await application.SendAsync("GET", "/auth/session")).Status);
    }

    /// <summary>
    /// OPS-BOOT-004 AC1 and AUTH-STEP-004 AC1: the break-glass session generates a
    /// replacement with no further step-up, which the next person uses, and the page
    /// is given the address the envelope names.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_AC1_ABreakGlassSessionGeneratesAReplacementAsync()
    {
        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        _deployment.Clock.Advance(TimeSpan.FromHours(1));

        Answer replaced = await owner.SendAsync("POST", Generate);

        Assert.Equal(StatusCodes.Status200OK, replaced.Status);
        Assert.Equal("https://identity.example.test/break-glass", replaced.Text("address"));
        Assert.Equal(_deployment.Clock.GetUtcNow(), replaced.Json().GetProperty("issuedAt").GetDateTimeOffset());
        Assert.Equal(_emergency, _deployment.BreakGlassAudit.Generated[^1].Acting);
        Assert.Equal(
            StatusCodes.Status200OK,
            (await PresentedAsync(new Browser(_deployment), replaced.Text("credential"))).Status);
    }

    /// <summary>
    /// OPS-BOOT-004 AC2: generation is audited against who generated it and alerted,
    /// to the owner with the owner's routine alerts turned off.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_AC2_GenerationIsAuditedAndReachesTheOwnerAsync()
    {
        _ = await GeneratedAsync();
        _ = await _deployment.CarryAlertsAsync();

        SubjectId administrator = _deployment.Directory.Created[^1].Subject;
        (SubjectId acting, _, BreakGlassCredentialId? replaced, _) =
            Assert.Single(_deployment.BreakGlassAudit.Generated);

        Assert.Equal(administrator, acting);
        Assert.Null(replaced);
        Assert.Contains(_deployment.Mail.Taken, mail => string.Equals(mail.Destination.Value, Owner, StringComparison.Ordinal));
        Assert.Contains(_deployment.Sms.Taken, message => string.Equals(message.Destination.Value, OwnerNumber, StringComparison.Ordinal));
        Assert.Equal("generated", Raised().Details["event"].GetString());
    }

    /// <summary>
    /// OPS-BOOT-004 AC3 and AC4: nothing reopens a code once answered, and a second
    /// generation answers a new one and invalidates the first; what is kept is a hash
    /// that holds neither.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_AC3_ASecondGenerationInvalidatesTheFirstAsync()
    {
        (Browser administrator, string first) = await AdministratorAsync();

        Answer second = await administrator.SendAsync("POST", Generate);
        string replacement = second.Text("credential");

        Assert.NotEqual(first, replacement);
        Assert.Equal(2, _deployment.BreakGlass.Issues.Count);
        Assert.NotNull(_deployment.BreakGlass.Issues[0].ReplacedAt);
        Assert.Equal(_deployment.BreakGlass.Issues[0].Id, _deployment.BreakGlassAudit.Generated[^1].Replaced);
        Assert.DoesNotContain(
            _deployment.BreakGlass.Issues,
            issue => issue.Hash.Encoded.Contains(first, StringComparison.Ordinal)
                || issue.Hash.Encoded.Contains(replacement, StringComparison.Ordinal));

        Answer stale = await PresentedAsync(new Browser(_deployment), first);
        Answer current = await PresentedAsync(new Browser(_deployment), replacement);

        Assert.Equal(StatusCodes.Status422UnprocessableEntity, stale.Status);
        Assert.Equal(ErrorCodes.BreakGlassInvalid.ToString(), stale.Text("code"));
        Assert.Equal(StatusCodes.Status200OK, current.Status);
    }

    /// <summary>
    /// OPS-BOOT-004 AC6: a group whose check symbol does not hold is refused before
    /// any issue is read, so no hash is compared.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_AC6_AWrongCheckIsRefusedBeforeAnyHashIsComparedAsync()
    {
        string credential = await GeneratedAsync();
        char check = credential[3];
        string mistyped = credential[..3] + (check == '0' ? '1' : '0') + credential[4..];
        int read = _deployment.BreakGlass.Reads;

        Answer refused = await PresentedAsync(new Browser(_deployment), mistyped);

        Assert.Equal(StatusCodes.Status422UnprocessableEntity, refused.Status);
        Assert.Equal(ErrorCodes.BreakGlassInvalid.ToString(), refused.Text("code"));
        Assert.Equal(read, _deployment.BreakGlass.Reads);
        Assert.True(Assert.Single(_deployment.BreakGlass.Issues).Stands);
    }

    /// <summary>
    /// OPS-BOOT-004 AC7: a source that keeps failing is held by its own delay, and the
    /// sixth attempt within the hour is refused whichever source makes it, the right
    /// code included, until the hour has passed.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_AC7_TheSixthAttemptInAnHourIsRefusedFromAnySourceAsync()
    {
        string credential = await GeneratedAsync();
        var browser = new Browser(_deployment);
        var repeated = IPAddress.Parse("198.51.100.1");

        for (int attempt = 0; attempt < 3; attempt++)
        {
            Assert.Equal(StatusCodes.Status422UnprocessableEntity, (await PresentedAsync(browser, Drawn(), repeated)).Status);
        }

        Answer delayed = await PresentedAsync(browser, credential, repeated);
        Answer fifth = await PresentedAsync(browser, Drawn(), IPAddress.Parse("198.51.100.2"));
        Answer sixth = await PresentedAsync(browser, credential, IPAddress.Parse("198.51.100.3"));

        Assert.Equal(StatusCodes.Status429TooManyRequests, delayed.Status);
        Assert.Equal(StatusCodes.Status422UnprocessableEntity, fifth.Status);
        Assert.Equal(StatusCodes.Status429TooManyRequests, sixth.Status);
        Assert.Equal(ErrorCodes.Throttled.ToString(), sixth.Text("code"));
        Assert.Equal(_deployment.Clock.GetUtcNow().AddHours(1), Lifts(sixth));
        Assert.Equal("3600", sixth.Header("Retry-After"));
        Assert.True(Assert.Single(_deployment.BreakGlass.Issues).Stands);

        _deployment.Clock.Advance(TimeSpan.FromHours(1));

        Assert.Equal(
            StatusCodes.Status200OK,
            (await PresentedAsync(browser, credential, IPAddress.Parse("198.51.100.4"))).Status);
    }

    /// <summary>
    /// BFF-ABUSE-001 AC2: a code presented from a source its own failures have delayed
    /// is answered 429 auth.throttled, with the instant the delay lifts in the body
    /// and the seconds to it in the header, the two agreeing.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task BFF_ABUSE_001_AC2_ADelayedBreakGlassCodeCarriesItsIntervalAsync()
    {
        string credential = await GeneratedAsync();
        var browser = new Browser(_deployment);
        var repeated = IPAddress.Parse("198.51.100.1");

        for (int attempt = 0; attempt < 3; attempt++)
        {
            _ = await PresentedAsync(browser, Drawn(), repeated);
        }

        Answer delayed = await PresentedAsync(browser, credential, repeated);

        Assert.Equal(StatusCodes.Status429TooManyRequests, delayed.Status);
        Assert.Equal(ErrorCodes.Throttled.ToString(), delayed.Text("code"));
        Assert.Equal(_deployment.Clock.GetUtcNow().AddSeconds(1), Lifts(delayed));
        Assert.Equal("1", delayed.Header("Retry-After"));
    }

    /// <summary>
    /// BFF-ABUSE-001 AC2 and AUTH-RECOV-002a: an approval past the day's cap for the
    /// account is answered 429 auth.throttled, with the instant the earliest approval
    /// counted against the cap leaves the day, and the header agrees with it.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task BFF_ABUSE_001_AC2_AnApprovalPastTheCapCarriesItsIntervalAsync()
    {
        _deployment.Configuration.Set(Settings.RecoveryRateLimitAccount, 1);

        string credential = await GeneratedAsync();
        SubjectId administrator = _deployment.Directory.Created[^1].Subject;
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        _deployment.Clock.Advance(TimeSpan.FromHours(1));

        Answer approved = await ApprovedAsync(owner, administrator);
        DateTimeOffset counted = _deployment.Clock.GetUtcNow();

        _deployment.Clock.Advance(TimeSpan.FromMinutes(1));

        Answer capped = await ApprovedAsync(owner, administrator);

        Assert.Equal(StatusCodes.Status200OK, approved.Status);
        Assert.Equal(StatusCodes.Status429TooManyRequests, capped.Status);
        Assert.Equal(ErrorCodes.Throttled.ToString(), capped.Text("code"));
        Assert.Equal(counted.AddDays(1), Lifts(capped));
        Assert.Equal("86340", capped.Header("Retry-After"));
    }

    /// <summary>
    /// FE-BG-001 AC3 and chapter 09 section 8: a browser holding a session for the
    /// domain presents the code, and the cookie is ignored rather than refused; the
    /// session the code opens replaces it.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task FE_BG_001_AC3_AStaleSessionCookieIsIgnoredAsync()
    {
        (Browser administrator, string credential) = await AdministratorAsync();
        string stale = administrator.Cookies[BrowserCookies.Session];

        Answer opened = await PresentedAsync(administrator, credential);

        Assert.Equal(StatusCodes.Status200OK, opened.Status);
        Assert.NotEqual(stale, administrator.Cookies[BrowserCookies.Session]);
        Assert.Equal(_emergency, Assert.Single(_deployment.BreakGlassAudit.Used).Emergency);
    }

    /// <summary>
    /// OPS-BOOT-004: generation asks for system administration and a stepped-up
    /// session, so an administrator whose proof is no longer recent generates nothing.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_004_GenerationAsksForASteppedUpSystemAdministratorAsync()
    {
        Browser member = await Flow.SignedInAsync(_deployment);
        SubjectId subject = _deployment.Directory.Created[^1].Subject;

        Answer withheld = await member.SendAsync("POST", Generate);

        _deployment.Gate.Grant(subject, Administration, Permissions.SystemAdminister);
        _deployment.Clock.Advance(TimeSpan.FromDays(1));

        Answer challenged = await member.SendAsync("POST", Generate);

        Assert.Equal(StatusCodes.Status403Forbidden, withheld.Status);
        Assert.Equal(ErrorCodes.Denied.ToString(), withheld.Text("code"));
        Assert.Equal(StatusCodes.Status403Forbidden, challenged.Status);
        Assert.Equal(ErrorCodes.StepUpRequired.ToString(), challenged.Text("code"));
        Assert.Empty(_deployment.BreakGlass.Issues);
    }

    /// <summary>
    /// OPS-BOOT-002: no factor can be enrolled on the reserved account, even from the
    /// session that passes every other gate.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task OPS_BOOT_002_NoSignInMethodIsGivenToTheReservedAccountAsync()
    {
        string credential = await GeneratedAsync();
        var owner = new Browser(_deployment);

        _ = await PresentedAsync(owner, credential);

        Answer password = await owner.SendAsync("POST", "/account/password", ("password", Flow.Password));

        Assert.Equal(StatusCodes.Status403Forbidden, password.Status);
        Assert.Equal(ErrorCodes.Denied.ToString(), password.Text("code"));
    }

    // The deployment is one origin here, so what a browser would follow across two
    // applications is followed as a path of the one it is talking to.
    private static string Local(string? where)
    {
        const string origin = "https://identity.example.test";

        ArgumentNullException.ThrowIfNull(where);

        return where.StartsWith(origin, StringComparison.Ordinal) ? where[origin.Length..] : where;
    }

    // The instant a throttled answer says its interval lifts (API-CONV-003).
    private static DateTimeOffset Lifts(Answer answer) =>
        answer.Json().GetProperty("details").GetProperty("retryAt").GetDateTimeOffset();

    private static Task<Answer> ApprovedAsync(Browser browser, SubjectId subject) =>
        browser.SendAsync(
            "POST",
            "/admin/recovery/approve",
            ("subject", subject.ToString()),
            ("reason", "The administrator lost every factor."),
            ("channelUsed", Flow.Address));

    private static Task<Answer> PresentedAsync(Browser browser, string credential, IPAddress? source = null) =>
        browser.SendAsync(
            "POST",
            Present,
            JsonSerializer.Serialize(new { credential }),
            source: source);

    private string Drawn() => BreakGlassCode.Draw(_randomness);

    private AlertRaised Raised() =>
        _deployment.Events.Of<AlertRaised>().Last(raised => raised.Condition is AlertCondition.BreakGlassUsed);

    private async Task<string> GeneratedAsync() => (await AdministratorAsync()).Credential;

    // A stepped-up system administrator generating the first issue from the management
    // application.
    private async Task<(Browser Browser, string Credential)> AdministratorAsync()
    {
        Browser administrator = await Flow.SignedInAsync(_deployment);

        _deployment.Gate.Grant(_deployment.Directory.Created[^1].Subject, Administration, Permissions.SystemAdminister);

        Answer generated = await administrator.SendAsync("POST", Generate);

        Assert.Equal(StatusCodes.Status200OK, generated.Status);

        return (administrator, generated.Text("credential"));
    }
}
