// <auto-generated />
using System;
using Janus.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Janus.Storage.Migrations;

[DbContext(typeof(StoreContext))]
[Migration("20260919104759_AddIdentifiers")]
partial class AddIdentifiers
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identity")
            .HasAnnotation("Npgsql:CollationDefinition:identity.identity_ci", "und-u-ks-level2,und-u-ks-level2,icu,False")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Janus.Storage.Identity.Accounts.AccountRecord", b =>
            {
                b.Property<Guid>("Subject")
                    .HasColumnType("uuid")
                    .HasColumnName("subject");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("DeletingBy")
                    .HasColumnType("text")
                    .HasColumnName("deleting_by");

                b.Property<DateTimeOffset?>("DeletingSince")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deleting_since");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("state");

                b.Property<string>("SuspendedBy")
                    .HasColumnType("text")
                    .HasColumnName("suspended_by");

                b.HasKey("Subject")
                    .HasName("pk_accounts");

                b.HasIndex("DeletingSince")
                    .HasDatabaseName("ix_accounts_deleting_since")
                    .HasFilter("deleting_since IS NOT NULL");

                b.ToTable("accounts", "identity", t =>
                    {
                        t.HasCheckConstraint("ck_accounts_deleting", "(deleting_by IS NULL) = (deleting_since IS NULL)");

                        t.HasCheckConstraint("ck_accounts_deleting_by", "deleting_by IS NULL OR deleting_by IN ('oob-request', 'self', 'takedown')");

                        t.HasCheckConstraint("ck_accounts_state", "state IN ('active', 'deleted', 'deleting', 'restricted', 'suspended')");

                        t.HasCheckConstraint("ck_accounts_suspended_by", "suspended_by IS NULL OR suspended_by IN ('administrator', 'self')");
                    });
            });

        modelBuilder.Entity("Janus.Storage.Identity.Identifiers.BackupSettingRecord", b =>
            {
                b.Property<Guid>("Subject")
                    .HasColumnType("uuid")
                    .HasColumnName("subject");

                b.Property<string>("Kind")
                    .HasColumnType("text")
                    .HasColumnName("kind");

                b.Property<Guid?>("Named")
                    .HasColumnType("uuid")
                    .HasColumnName("named");

                b.Property<string>("Rule")
                    .HasColumnType("text")
                    .HasColumnName("rule");

                b.HasKey("Subject", "Kind")
                    .HasName("pk_identifier_backup_settings");

                b.HasIndex("Named")
                    .HasDatabaseName("ix_identifier_backup_settings_named");

                b.ToTable("identifier_backup_settings", "identity", t =>
                    {
                        t.HasCheckConstraint("ck_identifier_backup_settings_kind", "kind IN ('email', 'phone', 'username')");

                        t.HasCheckConstraint("ck_identifier_backup_settings_rule", "rule IN ('all-verified', 'primary-only') OR rule IS NULL");

                        t.HasCheckConstraint("ck_identifier_backup_settings_setting", "(rule IS NULL) <> (named IS NULL)");
                    });
            });

        modelBuilder.Entity("Janus.Storage.Identity.Identifiers.IdentifierRecord", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("identifier_id");

                b.Property<DateTimeOffset>("AddedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("added_at");

                b.Property<byte[]>("Canonical")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("enc_canonical");

                b.Property<string>("CanonicalisationVersion")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("canonicalisation_version");

                b.Property<byte[]>("Entered")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("enc_entered");

                b.Property<byte[]>("Fingerprint")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("fingerprint");

                b.Property<bool>("IsLocked")
                    .HasColumnType("boolean")
                    .HasColumnName("is_locked");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("boolean")
                    .HasColumnName("is_primary");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("kind");

                b.Property<Guid>("Subject")
                    .HasColumnType("uuid")
                    .HasColumnName("subject");

                b.Property<DateTimeOffset?>("VerifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("verified_at");

                b.HasKey("Id")
                    .HasName("pk_identifiers");

                b.HasIndex("Kind", "Fingerprint")
                    .IsUnique()
                    .HasDatabaseName("ux_identifiers_fingerprint")
                    .HasFilter("fingerprint <> decode(repeat('00', 32), 'hex')");

                b.HasIndex("Subject", "Kind")
                    .HasDatabaseName("ix_identifiers_subject");

                b.ToTable("identifiers", "identity", t =>
                    {
                        t.HasCheckConstraint("ck_identifiers_fingerprint", "octet_length(fingerprint) = 32");

                        t.HasCheckConstraint("ck_identifiers_kind", "kind IN ('email', 'phone', 'username')");

                        t.HasCheckConstraint("ck_identifiers_primary", "NOT is_primary OR verified_at IS NOT NULL");
                    });
            });

        modelBuilder.Entity("Janus.Storage.Privacy.SubjectKeys.SubjectKeyRecord", b =>
            {
                b.Property<Guid>("Subject")
                    .HasColumnType("uuid")
                    .HasColumnName("subject");

                b.Property<byte>("FormatMarker")
                    .HasColumnType("smallint")
                    .HasColumnName("format_marker");

                b.Property<int>("KeyVersion")
                    .HasColumnType("integer")
                    .HasColumnName("key_version");

                b.Property<byte[]>("WrappedKey")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("wrapped_key");

                b.HasKey("Subject")
                    .HasName("pk_subject_keys");

                b.HasIndex("KeyVersion")
                    .HasDatabaseName("ix_subject_keys_key_version");

                b.ToTable("subject_keys", "identity", t =>
                    {
                        t.HasCheckConstraint("ck_subject_keys_format", "(format_marker = 1 AND octet_length(wrapped_key) = 40) OR (format_marker = 0 AND wrapped_key = decode(repeat('00', 32), 'hex'))");

                        t.HasCheckConstraint("ck_subject_keys_version", "key_version >= 1");
                    });
            });

        modelBuilder.Entity("Janus.Storage.Settings.SettingRecord", b =>
            {
                b.Property<string>("Key")
                    .HasColumnType("text")
                    .HasColumnName("key");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("Key")
                    .HasName("pk_settings");

                b.ToTable("settings", "identity");
            });

        modelBuilder.Entity("Janus.Storage.Identity.Identifiers.BackupSettingRecord", b =>
            {
                b.HasOne("Janus.Storage.Identity.Identifiers.IdentifierRecord", null)
                    .WithMany()
                    .HasForeignKey("Named")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_identifier_backup_settings_named");

                b.HasOne("Janus.Storage.Identity.Accounts.AccountRecord", null)
                    .WithMany()
                    .HasForeignKey("Subject")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_identifier_backup_settings_subject");
            });

        modelBuilder.Entity("Janus.Storage.Identity.Identifiers.IdentifierRecord", b =>
            {
                b.HasOne("Janus.Storage.Identity.Accounts.AccountRecord", null)
                    .WithMany()
                    .HasForeignKey("Subject")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_identifiers_subject");
            });
#pragma warning restore 612, 618
    }
}
