// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The Bidi_Class of a code point, which the Bidi Rule of RFC 5893 tests.
/// </summary>
internal enum BidiClass
{
    /// <summary>The AL value.</summary>
    AL = 0,

    /// <summary>The AN value.</summary>
    AN = 1,

    /// <summary>The B value.</summary>
    B = 2,

    /// <summary>The BN value.</summary>
    BN = 3,

    /// <summary>The CS value.</summary>
    CS = 4,

    /// <summary>The EN value.</summary>
    EN = 5,

    /// <summary>The ES value.</summary>
    ES = 6,

    /// <summary>The ET value.</summary>
    ET = 7,

    /// <summary>The FSI value.</summary>
    FSI = 8,

    /// <summary>The L value.</summary>
    L = 9,

    /// <summary>The LRE value.</summary>
    LRE = 10,

    /// <summary>The LRI value.</summary>
    LRI = 11,

    /// <summary>The LRO value.</summary>
    LRO = 12,

    /// <summary>The NSM value.</summary>
    NSM = 13,

    /// <summary>The ON value.</summary>
    ON = 14,

    /// <summary>The PDF value.</summary>
    PDF = 15,

    /// <summary>The PDI value.</summary>
    PDI = 16,

    /// <summary>The R value.</summary>
    R = 17,

    /// <summary>The RLE value.</summary>
    RLE = 18,

    /// <summary>The RLI value.</summary>
    RLI = 19,

    /// <summary>The RLO value.</summary>
    RLO = 20,

    /// <summary>The S value.</summary>
    S = 21,

    /// <summary>The WS value.</summary>
    WS = 22,
}
