// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The General_Category of a code point.
/// </summary>
internal enum GeneralCategory
{
    /// <summary>The Cc value.</summary>
    Cc = 0,

    /// <summary>The Cf value.</summary>
    Cf = 1,

    /// <summary>The Cn value.</summary>
    Cn = 2,

    /// <summary>The Co value.</summary>
    Co = 3,

    /// <summary>The Cs value.</summary>
    Cs = 4,

    /// <summary>The Ll value.</summary>
    Ll = 5,

    /// <summary>The Lm value.</summary>
    Lm = 6,

    /// <summary>The Lo value.</summary>
    Lo = 7,

    /// <summary>The Lt value.</summary>
    Lt = 8,

    /// <summary>The Lu value.</summary>
    Lu = 9,

    /// <summary>The Mc value.</summary>
    Mc = 10,

    /// <summary>The Me value.</summary>
    Me = 11,

    /// <summary>The Mn value.</summary>
    Mn = 12,

    /// <summary>The Nd value.</summary>
    Nd = 13,

    /// <summary>The Nl value.</summary>
    Nl = 14,

    /// <summary>The No value.</summary>
    No = 15,

    /// <summary>The Pc value.</summary>
    Pc = 16,

    /// <summary>The Pd value.</summary>
    Pd = 17,

    /// <summary>The Pe value.</summary>
    Pe = 18,

    /// <summary>The Pf value.</summary>
    Pf = 19,

    /// <summary>The Pi value.</summary>
    Pi = 20,

    /// <summary>The Po value.</summary>
    Po = 21,

    /// <summary>The Ps value.</summary>
    Ps = 22,

    /// <summary>The Sc value.</summary>
    Sc = 23,

    /// <summary>The Sk value.</summary>
    Sk = 24,

    /// <summary>The Sm value.</summary>
    Sm = 25,

    /// <summary>The So value.</summary>
    So = 26,

    /// <summary>The Zl value.</summary>
    Zl = 27,

    /// <summary>The Zp value.</summary>
    Zp = 28,

    /// <summary>The Zs value.</summary>
    Zs = 29,
}
