// <auto-generated />
// Generated from the IDNA mapping table of UTS #46 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The status the IDNA mapping table of UTS #46 section 5 gives a code point.
/// </summary>
internal enum IdnaStatus
{
    /// <summary>The Deviation value.</summary>
    Deviation = 0,

    /// <summary>The Disallowed value.</summary>
    Disallowed = 1,

    /// <summary>The Ignored value.</summary>
    Ignored = 2,

    /// <summary>The Mapped value.</summary>
    Mapped = 3,

    /// <summary>The Valid value.</summary>
    Valid = 4,
}
