// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The Joining_Type of a code point, which the contextual rule for the zero width
/// non-joiner tests (RFC 5892 appendix A.1).
/// </summary>
internal enum JoiningType
{
    /// <summary>The C value.</summary>
    C = 0,

    /// <summary>The D value.</summary>
    D = 1,

    /// <summary>The L value.</summary>
    L = 2,

    /// <summary>The R value.</summary>
    R = 3,

    /// <summary>The T value.</summary>
    T = 4,

    /// <summary>The U value.</summary>
    U = 5,
}
