// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The PRECIS derived property of a code point (RFC 8264 section 8).
/// </summary>
internal enum PrecisProperty
{
    /// <summary>The Disallowed value.</summary>
    Disallowed = 0,

    /// <summary>The Unassigned value.</summary>
    Unassigned = 1,

    /// <summary>The Pvalid value.</summary>
    Pvalid = 2,

    /// <summary>The ContextJ value.</summary>
    ContextJ = 3,

    /// <summary>The ContextO value.</summary>
    ContextO = 4,

    /// <summary>The FreeformPvalid value.</summary>
    FreeformPvalid = 5,
}
