// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The Script of a code point, followed by the multi-script writing systems UTS #39 section
/// 5.1 augments a script set with.
/// </summary>
internal enum ScriptCode
{
    /// <summary>The Adlm value.</summary>
    Adlm = 0,

    /// <summary>The Aghb value.</summary>
    Aghb = 1,

    /// <summary>The Ahom value.</summary>
    Ahom = 2,

    /// <summary>The Arab value.</summary>
    Arab = 3,

    /// <summary>The Armi value.</summary>
    Armi = 4,

    /// <summary>The Armn value.</summary>
    Armn = 5,

    /// <summary>The Avst value.</summary>
    Avst = 6,

    /// <summary>The Bali value.</summary>
    Bali = 7,

    /// <summary>The Bamu value.</summary>
    Bamu = 8,

    /// <summary>The Bass value.</summary>
    Bass = 9,

    /// <summary>The Batk value.</summary>
    Batk = 10,

    /// <summary>The Beng value.</summary>
    Beng = 11,

    /// <summary>The Berf value.</summary>
    Berf = 12,

    /// <summary>The Bhks value.</summary>
    Bhks = 13,

    /// <summary>The Bopo value.</summary>
    Bopo = 14,

    /// <summary>The Brah value.</summary>
    Brah = 15,

    /// <summary>The Brai value.</summary>
    Brai = 16,

    /// <summary>The Bugi value.</summary>
    Bugi = 17,

    /// <summary>The Buhd value.</summary>
    Buhd = 18,

    /// <summary>The Cakm value.</summary>
    Cakm = 19,

    /// <summary>The Cans value.</summary>
    Cans = 20,

    /// <summary>The Cari value.</summary>
    Cari = 21,

    /// <summary>The Cham value.</summary>
    Cham = 22,

    /// <summary>The Cher value.</summary>
    Cher = 23,

    /// <summary>The Chrs value.</summary>
    Chrs = 24,

    /// <summary>The Copt value.</summary>
    Copt = 25,

    /// <summary>The Cpmn value.</summary>
    Cpmn = 26,

    /// <summary>The Cprt value.</summary>
    Cprt = 27,

    /// <summary>The Cyrl value.</summary>
    Cyrl = 28,

    /// <summary>The Deva value.</summary>
    Deva = 29,

    /// <summary>The Diak value.</summary>
    Diak = 30,

    /// <summary>The Dogr value.</summary>
    Dogr = 31,

    /// <summary>The Dsrt value.</summary>
    Dsrt = 32,

    /// <summary>The Dupl value.</summary>
    Dupl = 33,

    /// <summary>The Egyp value.</summary>
    Egyp = 34,

    /// <summary>The Elba value.</summary>
    Elba = 35,

    /// <summary>The Elym value.</summary>
    Elym = 36,

    /// <summary>The Ethi value.</summary>
    Ethi = 37,

    /// <summary>The Gara value.</summary>
    Gara = 38,

    /// <summary>The Geor value.</summary>
    Geor = 39,

    /// <summary>The Glag value.</summary>
    Glag = 40,

    /// <summary>The Gong value.</summary>
    Gong = 41,

    /// <summary>The Gonm value.</summary>
    Gonm = 42,

    /// <summary>The Goth value.</summary>
    Goth = 43,

    /// <summary>The Gran value.</summary>
    Gran = 44,

    /// <summary>The Grek value.</summary>
    Grek = 45,

    /// <summary>The Gujr value.</summary>
    Gujr = 46,

    /// <summary>The Gukh value.</summary>
    Gukh = 47,

    /// <summary>The Guru value.</summary>
    Guru = 48,

    /// <summary>The Hang value.</summary>
    Hang = 49,

    /// <summary>The Hani value.</summary>
    Hani = 50,

    /// <summary>The Hano value.</summary>
    Hano = 51,

    /// <summary>The Hatr value.</summary>
    Hatr = 52,

    /// <summary>The Hebr value.</summary>
    Hebr = 53,

    /// <summary>The Hira value.</summary>
    Hira = 54,

    /// <summary>The Hluw value.</summary>
    Hluw = 55,

    /// <summary>The Hmng value.</summary>
    Hmng = 56,

    /// <summary>The Hmnp value.</summary>
    Hmnp = 57,

    /// <summary>The Hrkt value.</summary>
    Hrkt = 58,

    /// <summary>The Hung value.</summary>
    Hung = 59,

    /// <summary>The Ital value.</summary>
    Ital = 60,

    /// <summary>The Java value.</summary>
    Java = 61,

    /// <summary>The Kali value.</summary>
    Kali = 62,

    /// <summary>The Kana value.</summary>
    Kana = 63,

    /// <summary>The Kawi value.</summary>
    Kawi = 64,

    /// <summary>The Khar value.</summary>
    Khar = 65,

    /// <summary>The Khmr value.</summary>
    Khmr = 66,

    /// <summary>The Khoj value.</summary>
    Khoj = 67,

    /// <summary>The Kits value.</summary>
    Kits = 68,

    /// <summary>The Knda value.</summary>
    Knda = 69,

    /// <summary>The Krai value.</summary>
    Krai = 70,

    /// <summary>The Kthi value.</summary>
    Kthi = 71,

    /// <summary>The Lana value.</summary>
    Lana = 72,

    /// <summary>The Laoo value.</summary>
    Laoo = 73,

    /// <summary>The Latn value.</summary>
    Latn = 74,

    /// <summary>The Lepc value.</summary>
    Lepc = 75,

    /// <summary>The Limb value.</summary>
    Limb = 76,

    /// <summary>The Lina value.</summary>
    Lina = 77,

    /// <summary>The Linb value.</summary>
    Linb = 78,

    /// <summary>The Lisu value.</summary>
    Lisu = 79,

    /// <summary>The Lyci value.</summary>
    Lyci = 80,

    /// <summary>The Lydi value.</summary>
    Lydi = 81,

    /// <summary>The Mahj value.</summary>
    Mahj = 82,

    /// <summary>The Maka value.</summary>
    Maka = 83,

    /// <summary>The Mand value.</summary>
    Mand = 84,

    /// <summary>The Mani value.</summary>
    Mani = 85,

    /// <summary>The Marc value.</summary>
    Marc = 86,

    /// <summary>The Medf value.</summary>
    Medf = 87,

    /// <summary>The Mend value.</summary>
    Mend = 88,

    /// <summary>The Merc value.</summary>
    Merc = 89,

    /// <summary>The Mero value.</summary>
    Mero = 90,

    /// <summary>The Mlym value.</summary>
    Mlym = 91,

    /// <summary>The Modi value.</summary>
    Modi = 92,

    /// <summary>The Mong value.</summary>
    Mong = 93,

    /// <summary>The Mroo value.</summary>
    Mroo = 94,

    /// <summary>The Mtei value.</summary>
    Mtei = 95,

    /// <summary>The Mult value.</summary>
    Mult = 96,

    /// <summary>The Mymr value.</summary>
    Mymr = 97,

    /// <summary>The Nagm value.</summary>
    Nagm = 98,

    /// <summary>The Nand value.</summary>
    Nand = 99,

    /// <summary>The Narb value.</summary>
    Narb = 100,

    /// <summary>The Nbat value.</summary>
    Nbat = 101,

    /// <summary>The Newa value.</summary>
    Newa = 102,

    /// <summary>The Nkoo value.</summary>
    Nkoo = 103,

    /// <summary>The Nshu value.</summary>
    Nshu = 104,

    /// <summary>The Ogam value.</summary>
    Ogam = 105,

    /// <summary>The Olck value.</summary>
    Olck = 106,

    /// <summary>The Onao value.</summary>
    Onao = 107,

    /// <summary>The Orkh value.</summary>
    Orkh = 108,

    /// <summary>The Orya value.</summary>
    Orya = 109,

    /// <summary>The Osge value.</summary>
    Osge = 110,

    /// <summary>The Osma value.</summary>
    Osma = 111,

    /// <summary>The Ougr value.</summary>
    Ougr = 112,

    /// <summary>The Palm value.</summary>
    Palm = 113,

    /// <summary>The Pauc value.</summary>
    Pauc = 114,

    /// <summary>The Perm value.</summary>
    Perm = 115,

    /// <summary>The Phag value.</summary>
    Phag = 116,

    /// <summary>The Phli value.</summary>
    Phli = 117,

    /// <summary>The Phlp value.</summary>
    Phlp = 118,

    /// <summary>The Phnx value.</summary>
    Phnx = 119,

    /// <summary>The Plrd value.</summary>
    Plrd = 120,

    /// <summary>The Prti value.</summary>
    Prti = 121,

    /// <summary>The Rjng value.</summary>
    Rjng = 122,

    /// <summary>The Rohg value.</summary>
    Rohg = 123,

    /// <summary>The Runr value.</summary>
    Runr = 124,

    /// <summary>The Samr value.</summary>
    Samr = 125,

    /// <summary>The Sarb value.</summary>
    Sarb = 126,

    /// <summary>The Saur value.</summary>
    Saur = 127,

    /// <summary>The Sgnw value.</summary>
    Sgnw = 128,

    /// <summary>The Shaw value.</summary>
    Shaw = 129,

    /// <summary>The Shrd value.</summary>
    Shrd = 130,

    /// <summary>The Sidd value.</summary>
    Sidd = 131,

    /// <summary>The Sidt value.</summary>
    Sidt = 132,

    /// <summary>The Sind value.</summary>
    Sind = 133,

    /// <summary>The Sinh value.</summary>
    Sinh = 134,

    /// <summary>The Sogd value.</summary>
    Sogd = 135,

    /// <summary>The Sogo value.</summary>
    Sogo = 136,

    /// <summary>The Sora value.</summary>
    Sora = 137,

    /// <summary>The Soyo value.</summary>
    Soyo = 138,

    /// <summary>The Sund value.</summary>
    Sund = 139,

    /// <summary>The Sunu value.</summary>
    Sunu = 140,

    /// <summary>The Sylo value.</summary>
    Sylo = 141,

    /// <summary>The Syrc value.</summary>
    Syrc = 142,

    /// <summary>The Tagb value.</summary>
    Tagb = 143,

    /// <summary>The Takr value.</summary>
    Takr = 144,

    /// <summary>The Tale value.</summary>
    Tale = 145,

    /// <summary>The Talu value.</summary>
    Talu = 146,

    /// <summary>The Taml value.</summary>
    Taml = 147,

    /// <summary>The Tang value.</summary>
    Tang = 148,

    /// <summary>The Tavt value.</summary>
    Tavt = 149,

    /// <summary>The Tayo value.</summary>
    Tayo = 150,

    /// <summary>The Telu value.</summary>
    Telu = 151,

    /// <summary>The Tfng value.</summary>
    Tfng = 152,

    /// <summary>The Tglg value.</summary>
    Tglg = 153,

    /// <summary>The Thaa value.</summary>
    Thaa = 154,

    /// <summary>The Thai value.</summary>
    Thai = 155,

    /// <summary>The Tibt value.</summary>
    Tibt = 156,

    /// <summary>The Tirh value.</summary>
    Tirh = 157,

    /// <summary>The Tnsa value.</summary>
    Tnsa = 158,

    /// <summary>The Todr value.</summary>
    Todr = 159,

    /// <summary>The Tols value.</summary>
    Tols = 160,

    /// <summary>The Toto value.</summary>
    Toto = 161,

    /// <summary>The Tutg value.</summary>
    Tutg = 162,

    /// <summary>The Ugar value.</summary>
    Ugar = 163,

    /// <summary>The Vaii value.</summary>
    Vaii = 164,

    /// <summary>The Vith value.</summary>
    Vith = 165,

    /// <summary>The Wara value.</summary>
    Wara = 166,

    /// <summary>The Wcho value.</summary>
    Wcho = 167,

    /// <summary>The Xpeo value.</summary>
    Xpeo = 168,

    /// <summary>The Xsux value.</summary>
    Xsux = 169,

    /// <summary>The Yezi value.</summary>
    Yezi = 170,

    /// <summary>The Yiii value.</summary>
    Yiii = 171,

    /// <summary>The Zanb value.</summary>
    Zanb = 172,

    /// <summary>The Zinh value.</summary>
    Zinh = 173,

    /// <summary>The Zyyy value.</summary>
    Zyyy = 174,

    /// <summary>The Zzzz value.</summary>
    Zzzz = 175,

    /// <summary>The Hanb value.</summary>
    Hanb = 176,

    /// <summary>The Hntl value.</summary>
    Hntl = 177,

    /// <summary>The Jpan value.</summary>
    Jpan = 178,

    /// <summary>The Kore value.</summary>
    Kore = 179,
}
