// <auto-generated />
// Generated from the Unicode Character Database 17.0.0 by tools/Janus.UnicodeTables.
// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.

namespace Janus.Core.Unicode;

/// <summary>
/// The Unicode version every table is generated from, and the canonicalisation version
/// recorded beside every fingerprint (IDN-ACCT-004).
/// </summary>
internal static class UnicodeVersion
{
    /// <summary>The version.</summary>
    internal const string Value = "17.0.0";
}
