using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Janus.UnicodeTables;

/// <summary>
/// One generated source file under <c>Janus.Core</c>.
/// </summary>
/// <remarks>
/// The file is written with line feeds and without a byte order mark whatever the
/// machine writing it, because the gate compares it to the checked-in copy byte for
/// byte.
/// </remarks>
internal sealed class SourceFile
{
    private const int PerLine = 12;

    private const int Width = 92;

    private static readonly UTF8Encoding Encoding = new(encoderShouldEmitUTF8Identifier: false);

    private readonly StringBuilder _text = new();

    /// <summary>
    /// Opens a file in the namespace the tables live in.
    /// </summary>
    /// <param name="version">The Unicode version the tables are generated from.</param>
    internal SourceFile(string version)
    {
        Line("// <auto-generated />");
        Line("// Generated from the Unicode Character Database " + version + " by tools/Janus.UnicodeTables.");
        Line("// Do not edit. The gate of CONV-GATE-001 generates this file again and fails on a diff.");
        Line();
        Line("namespace Janus.Core.Unicode;");
    }

    /// <summary>
    /// Opens a static class holding tables.
    /// </summary>
    /// <param name="name">The class name.</param>
    /// <param name="summary">What the class holds.</param>
    internal void OpenClass(string name, string summary)
    {
        Line();
        Summary(summary);
        Line("internal static class " + name);
        Line("{");
    }

    /// <summary>
    /// Writes an enumeration whose members are the values of a Unicode property.
    /// </summary>
    /// <param name="name">The enumeration name.</param>
    /// <param name="summary">What the enumeration stands for.</param>
    /// <param name="members">The member names, in identifier order.</param>
    internal void Enumeration(string name, string summary, IReadOnlyList<string> members)
    {
        ArgumentNullException.ThrowIfNull(members);

        Line();
        Summary(summary);
        Line("internal enum " + name);
        Line("{");

        for (int index = 0; index < members.Count; index++)
        {
            Line("    /// <summary>The " + members[index] + " value.</summary>");
            Line("    " + members[index] + " = " + index.ToString(CultureInfo.InvariantCulture) + ",");

            if (index < members.Count - 1)
            {
                Line();
            }
        }

        Line("}");
    }

    /// <summary>
    /// Writes a string constant.
    /// </summary>
    /// <param name="name">The constant name.</param>
    /// <param name="summary">What the constant holds.</param>
    /// <param name="value">The value.</param>
    internal void Constant(string name, string summary, string value)
    {
        Line("    /// <summary>" + summary + "</summary>");
        Line("    internal const string " + name + " = \"" + value + "\";");
    }

    /// <summary>
    /// Closes the open class.
    /// </summary>
    internal void CloseClass() => Line("}");

    /// <summary>
    /// Writes an array field.
    /// </summary>
    /// <param name="type">The element type.</param>
    /// <param name="name">The field name.</param>
    /// <param name="summary">What the field holds.</param>
    /// <param name="values">The elements, already formatted.</param>
    /// <param name="first">Whether this is the first member of its class.</param>
    internal void Array(string type, string name, string summary, IReadOnlyList<string> values, bool first)
    {
        ArgumentNullException.ThrowIfNull(values);

        if (!first)
        {
            Line();
        }

        Line("    /// <summary>" + summary + "</summary>");
        Line("    internal static readonly " + type + "[] " + name + " =");
        Line("    [");

        for (int index = 0; index < values.Count; index += PerLine)
        {
            var line = new StringBuilder("        ");

            for (int offset = index; offset < values.Count && offset < index + PerLine; offset++)
            {
                line.Append(values[offset]).Append(',');

                if (offset < values.Count - 1 && offset < index + PerLine - 1)
                {
                    line.Append(' ');
                }
            }

            Line(line.ToString());
        }

        Line("    ];");
    }

    /// <summary>
    /// Writes the file.
    /// </summary>
    /// <param name="path">Where to write it.</param>
    internal void Save(string path) => File.WriteAllText(path, _text.ToString(), Encoding);

    /// <summary>
    /// Formats a value as a decimal literal.
    /// </summary>
    /// <param name="value">The value.</param>
    /// <returns>The literal.</returns>
    internal static string Decimal(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>
    /// Formats a code point as a hexadecimal literal.
    /// </summary>
    /// <param name="value">The code point.</param>
    /// <returns>The literal.</returns>
    internal static string Hex(int value) =>
        "0x" + value.ToString("X4", CultureInfo.InvariantCulture);

    /// <summary>
    /// Formats a packed pair as a hexadecimal literal.
    /// </summary>
    /// <param name="value">The pair.</param>
    /// <returns>The literal.</returns>
    internal static string HexPair(long value) =>
        "0x" + value.ToString("X11", CultureInfo.InvariantCulture);

    private void Summary(string summary)
    {
        Line("/// <summary>");

        var line = new StringBuilder("///");

        foreach (string word in summary.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (line.Length + 1 + word.Length > Width)
            {
                Line(line.ToString());
                line = new StringBuilder("///");
            }

            line.Append(' ').Append(word);
        }

        Line(line.ToString());
        Line("/// </summary>");
    }

    private void Line() => _text.Append('\n');

    private void Line(string text) => _text.Append(text.TrimEnd()).Append('\n');
}
