using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Janus.Core;
using Janus.Core.Configuration;
using Janus.Hosting.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Janus.Hosting;

/// <summary>
/// Reads whether the deployment named every key it has to name, before the web server
/// starts.
/// </summary>
/// <param name="scopes">Where the scope the check reads in comes from.</param>
/// <remarks>
/// Implements LIB-HOST-001 AC2 and AC4, and chapter 10 section 4. It runs before every
/// other check that reads the configuration, so a key left unnamed is reported by its
/// own name and code rather than by whichever check happens to read it first. The
/// records of processing are generated by every deployment, since the library serves
/// them, so the hosting environment is always a key the deployment names (entry 273).
/// </remarks>
internal sealed class SettingsValidationService(IServiceScopeFactory scopes) : IHostedService
{
    /// <inheritdoc/>
    /// <exception cref="StartupException">
    /// A key the deployment has to name carries no value, or a value it named cannot be
    /// read.
    /// </exception>
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope = scopes.CreateAsyncScope();

        IConfigurationStore configuration = scope.ServiceProvider.GetRequiredService<IConfigurationStore>();
        var naming = new SettingNaming(configuration, cancellationToken);
        var named = new HashSet<ConfigurationKey>();

        foreach (Setting setting in Settings.Required)
        {
            if (Held(await setting.Apply(naming).ConfigureAwait(false)))
            {
                _ = named.Add(setting.Key);
            }
        }

        HostingLocation? location = named.Contains(Settings.HostingLocation.Key)
            ? Held(await configuration.ReadAsync(Settings.HostingLocation, cancellationToken).ConfigureAwait(false))
            : null;

        BlocklistSource source = Held(
            await configuration.ReadAsync(Settings.PasswordBlocklistSource, cancellationToken).ConfigureAwait(false));

        IReadOnlySet<BlocklistRejectionSource> sources = Held(
            await configuration.ReadAsync(Settings.PasswordBlocklistSources, cancellationToken).ConfigureAwait(false));

        Settings.ThrowIfIncomplete(named, location, source, sources, recordsOfProcessing: true);
    }

    /// <inheritdoc/>
    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private static TValue Held<TValue>(Result<TValue> read) =>
        read.Match(
            value => value,
            failure => throw new StartupException(
                "A value the deployment named cannot be read.",
                failure));
}
