using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using Janus.Hosting.Tests.Bff;
using Xunit;

namespace Janus.Hosting.Tests;

/// <summary>
/// The library's identity as the build writes it: constants generated after MinVer has
/// set the version, never committed, beside no project file that sets a version of its
/// own (CONV-CODE-004, LIB-VER-001, D-168).
/// </summary>
[Trait("kind", "contract")]
public sealed class LibraryIdentityTests
{
    // The folders the build reads a project file from, beside the root's own.
    private static readonly string[] Folders = ["src", "tests", "tools"];

    // A property element that would set a version beside the one MinVer derives from the
    // release tag. The central package list's items carry a Version attribute, which
    // pins a dependency and is not an element.
    private static readonly Regex SetsAVersion = new(
        @"<(?:Version|VersionPrefix|VersionSuffix|PackageVersion|AssemblyVersion|FileVersion|InformationalVersion)(?:\s+Condition=""[^""]*"")?\s*>",
        RegexOptions.None,
        TimeSpan.FromSeconds(5));

    /// <summary>
    /// CONV-CODE-004 AC3: the version constant is the package version of the build, the
    /// informational version the build stamps without what follows its <c>+</c>.
    /// </summary>
    [Fact]
    public void CONV_CODE_004_AC3_TheVersionConstantIsThePackageVersionWithoutBuildMetadata()
    {
        string stamped = typeof(LibraryPackage).Assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()!
            .InformationalVersion;

        Assert.Equal(LibraryPackage.Version, stamped.Split('+')[0]);
        Assert.DoesNotContain('+', LibraryPackage.Version);
    }

    /// <summary>
    /// CONV-CODE-004 AC3: the constants are written into the intermediate output, marked
    /// as generated, and no source the repository holds declares them.
    /// </summary>
    [Fact]
    public void CONV_CODE_004_AC3_TheConstantsAreGeneratedAndNeverCommitted()
    {
        string project = Path.Combine(Repository.Root(), "src", "Janus.Hosting");

        string[] generated = Directory.GetFiles(
            Path.Combine(project, "obj"),
            "LibraryPackage.g.cs",
            SearchOption.AllDirectories);

        string[] committed = Directory
            .EnumerateFiles(Path.Combine(Repository.Root(), "src"), "*.cs", SearchOption.AllDirectories)
            .Where(file => !Built(file))
            .Where(file => File.ReadAllText(file).Contains("class LibraryPackage", StringComparison.Ordinal))
            .ToArray();

        Assert.NotEmpty(generated);
        Assert.All(generated, file => Assert.StartsWith(
            "// <auto-generated/>",
            File.ReadAllText(file),
            StringComparison.Ordinal));
        Assert.Contains(
            "[Oo]bj/",
            File.ReadAllLines(Path.Combine(Repository.Root(), ".gitignore")));
        Assert.Empty(committed);
    }

    /// <summary>
    /// CONV-CODE-004 AC3, LIB-VER-001: no project, <c>.props</c> or <c>.targets</c> file
    /// sets a version, so the tag is the one place a version comes from.
    /// </summary>
    [Fact]
    public void CONV_CODE_004_AC3_NoProjectFileSetsAVersion()
    {
        string[] setting = Directory
            .EnumerateFiles(Repository.Root(), "*.*", SearchOption.TopDirectoryOnly)
            .Concat(Folders.SelectMany(folder => Directory.EnumerateFiles(
                Path.Combine(Repository.Root(), folder),
                "*.*",
                SearchOption.AllDirectories)))
            .Where(file => !Built(file))
            .Where(file => Path.GetExtension(file) is ".csproj" or ".props" or ".targets")
            .Where(file => SetsAVersion.IsMatch(File.ReadAllText(file)))
            .Select(file => Path.GetRelativePath(Repository.Root(), file))
            .ToArray();

        Assert.Empty(setting);
    }

    private static bool Built(string file) =>
        file.Split(Path.DirectorySeparatorChar).Any(folder => folder is "bin" or "obj");
}
