using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Npgsql;
using Xunit;

namespace Janus.Storage.Tests;

/// <summary>
/// The library-owned schema as a host reads it: every table and view in the library's
/// schema, with its columns, constraints and indexes, read from a migrated database
/// (LIB-API-001, LIB-TEST-002).
/// </summary>
/// <remarks>
/// The schema is read from the database and not from the model, because the view a
/// host's filter reads and the partitioning of the audit records exist only in the
/// migrations. A month's partition is created by the day the migration or the sweep
/// runs, so the leaf partitions are not part of the contract; the partitioned tables
/// above them are.
/// </remarks>
[Trait("kind", "integration")]
public sealed class SchemaContractTests(DatabaseFixture database) : IClassFixture<DatabaseFixture>
{
    // One line for each table or view, followed by one line for each column in its
    // order, each constraint and each index not backing a constraint, in the order of
    // the relation's name and then of the item's.
    private const string Rendered =
        """
        WITH relations AS (
            SELECT held.oid, held.relname, held.relkind, held.relispartition
            FROM pg_class AS held
            JOIN pg_namespace AS owner ON owner.oid = held.relnamespace
            WHERE owner.nspname = 'identity'
                AND held.relkind IN ('r', 'p', 'v')
                AND NOT (held.relispartition AND held.relkind = 'r')
        )
        SELECT line
        FROM (
            SELECT relation.relname AS relation, 0 AS part, '' AS item,
                CASE relation.relkind WHEN 'v' THEN 'view ' ELSE 'table ' END || relation.relname
                    || CASE WHEN relation.relispartition
                        THEN ' partition of ' || parent.relname || ' '
                            || pg_get_expr(child.relpartbound, child.oid)
                        ELSE '' END
                    || CASE WHEN relation.relkind = 'p'
                        THEN ' partitioned by ' || pg_get_partkeydef(relation.oid)
                        ELSE '' END AS line
            FROM relations AS relation
            JOIN pg_class AS child ON child.oid = relation.oid
            LEFT JOIN pg_inherits AS inherited ON inherited.inhrelid = relation.oid
            LEFT JOIN pg_class AS parent ON parent.oid = inherited.inhparent
            UNION ALL
            SELECT relation.relname, 1, lpad(field.attnum::text, 4, '0'),
                '  column ' || field.attname || ' ' || format_type(field.atttypid, field.atttypmod)
                    || CASE WHEN field.attnotnull THEN ' not null' ELSE '' END
                    || CASE field.attidentity
                        WHEN 'a' THEN ' generated always as identity'
                        WHEN 'd' THEN ' generated by default as identity'
                        ELSE '' END
                    || CASE
                        WHEN field.attgenerated = 's'
                            THEN ' generated always as (' || pg_get_expr(fallback.adbin, fallback.adrelid) || ') stored'
                        WHEN fallback.adbin IS NOT NULL
                            THEN ' default ' || pg_get_expr(fallback.adbin, fallback.adrelid)
                        ELSE '' END
            FROM relations AS relation
            JOIN pg_attribute AS field
                ON field.attrelid = relation.oid AND field.attnum > 0 AND NOT field.attisdropped
            LEFT JOIN pg_attrdef AS fallback
                ON fallback.adrelid = relation.oid AND fallback.adnum = field.attnum
            UNION ALL
            SELECT relation.relname, 2, bound.conname,
                '  constraint ' || bound.conname || ' ' || pg_get_constraintdef(bound.oid)
            FROM relations AS relation
            JOIN pg_constraint AS bound ON bound.conrelid = relation.oid
            UNION ALL
            SELECT relation.relname, 3, named.relname,
                '  index ' || named.relname
                    || CASE WHEN indexed.indisunique THEN ' unique ' ELSE ' ' END
                    || regexp_replace(pg_get_indexdef(indexed.indexrelid), '^.*? USING ', 'using ')
            FROM relations AS relation
            JOIN pg_index AS indexed ON indexed.indrelid = relation.oid
            JOIN pg_class AS named ON named.oid = indexed.indexrelid
            WHERE NOT EXISTS (
                SELECT 1 FROM pg_constraint AS bound
                WHERE bound.conindid = indexed.indexrelid AND bound.contype IN ('p', 'u', 'x'))
        ) AS lines
        ORDER BY relation, part, item
        """;

    /// <summary>
    /// LIB-API-001 AC2: the library-owned schema is the committed one, so a table,
    /// column, constraint or index that changes fails here until the change is written
    /// into the file beside this test, where it is the reviewable diff.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task LIB_API_001_AC2_TheLibraryOwnedSchemaIsTheContractAsync() =>
        Assert.Equal(
            Repository.ReadText("tests/Janus.Storage.Tests/schema.txt")
                .ReplaceLineEndings("\n")
                .Split('\n', StringSplitOptions.RemoveEmptyEntries),
            await SchemaAsync());

    /// <summary>
    /// LIB-TEST-002 AC2: the ancestry closure is queried from a host's own SQL and
    /// cannot be restructured without a major version, so its structure is stated here
    /// as well as in the committed schema, and a change to it fails both.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task LIB_TEST_002_AC2_TheAncestryClosureStructureIsTheContractAsync()
    {
        IReadOnlyList<string> schema = await SchemaAsync();

        Assert.Equal(
            [
                "table ancestry",
                "  column resource_type text not null",
                "  column resource_id text not null",
                "  column ancestor_type text not null",
                "  column ancestor_id text not null",
                "  column depth integer not null",
                "  column organization uuid not null",
                "  constraint ck_ancestry_depth CHECK ((depth >= 0))",
                "  constraint pk_ancestry PRIMARY KEY (resource_type, resource_id, ancestor_type, ancestor_id)",
                "  index ix_ancestry_ancestor using btree (ancestor_type, ancestor_id)",
            ],
            schema
                .SkipWhile(line => line != "table ancestry")
                .TakeWhile((line, at) => at == 0 || line.StartsWith("  ", StringComparison.Ordinal)));
    }

    private async Task<IReadOnlyList<string>> SchemaAsync()
    {
        await using NpgsqlConnection connection = await database.OpenAsync();

        return [.. await connection.QueryAsync<string>(Rendered)];
    }
}
