using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Janus.Core;
using Janus.Privacy.SubjectKeys;
using Janus.Storage.Privacy.SubjectKeys;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql;
using Xunit;

namespace Janus.Storage.Tests;

/// <summary>
/// The library-owned schema as a host reads it: every table and view in the library's
/// schema, with its columns, constraints and indexes, the type every instant is stored
/// as, and the columns that refuse the deployment key's identifier, read from a migrated
/// database (LIB-API-001, LIB-TEST-002, PRIV-RET-003, PRIV-RIGHT-005a).
/// </summary>
/// <remarks>
/// The schema is read from the database and not from the model, because the view a
/// host's filter reads and the partitioning of the audit records exist only in the
/// migrations. A month's partition is created by the day the migration or the sweep
/// runs, so the leaf partitions are not part of the contract; the partitioned tables
/// above them are.
/// </remarks>
[Trait("kind", "integration")]
public sealed class SchemaContractTests(DatabaseFixture database) : IClassFixture<DatabaseFixture>
{
    // One line for each table or view, followed by one line for each column in its
    // order, each constraint and each index not backing a constraint, in the order of
    // the relation's name and then of the item's.
    private const string Rendered =
        """
        WITH relations AS (
            SELECT held.oid, held.relname, held.relkind, held.relispartition
            FROM pg_class AS held
            JOIN pg_namespace AS owner ON owner.oid = held.relnamespace
            WHERE owner.nspname = 'identity'
                AND held.relkind IN ('r', 'p', 'v')
                AND NOT (held.relispartition AND held.relkind = 'r')
        )
        SELECT line
        FROM (
            SELECT relation.relname AS relation, 0 AS part, '' AS item,
                CASE relation.relkind WHEN 'v' THEN 'view ' ELSE 'table ' END || relation.relname
                    || CASE WHEN relation.relispartition
                        THEN ' partition of ' || parent.relname || ' '
                            || pg_get_expr(child.relpartbound, child.oid)
                        ELSE '' END
                    || CASE WHEN relation.relkind = 'p'
                        THEN ' partitioned by ' || pg_get_partkeydef(relation.oid)
                        ELSE '' END AS line
            FROM relations AS relation
            JOIN pg_class AS child ON child.oid = relation.oid
            LEFT JOIN pg_inherits AS inherited ON inherited.inhrelid = relation.oid
            LEFT JOIN pg_class AS parent ON parent.oid = inherited.inhparent
            UNION ALL
            SELECT relation.relname, 1, lpad(field.attnum::text, 4, '0'),
                '  column ' || field.attname || ' ' || format_type(field.atttypid, field.atttypmod)
                    || CASE WHEN field.attnotnull THEN ' not null' ELSE '' END
                    || CASE field.attidentity
                        WHEN 'a' THEN ' generated always as identity'
                        WHEN 'd' THEN ' generated by default as identity'
                        ELSE '' END
                    || CASE
                        WHEN field.attgenerated = 's'
                            THEN ' generated always as (' || pg_get_expr(fallback.adbin, fallback.adrelid) || ') stored'
                        WHEN fallback.adbin IS NOT NULL
                            THEN ' default ' || pg_get_expr(fallback.adbin, fallback.adrelid)
                        ELSE '' END
            FROM relations AS relation
            JOIN pg_attribute AS field
                ON field.attrelid = relation.oid AND field.attnum > 0 AND NOT field.attisdropped
            LEFT JOIN pg_attrdef AS fallback
                ON fallback.adrelid = relation.oid AND fallback.adnum = field.attnum
            UNION ALL
            SELECT relation.relname, 2, bound.conname,
                '  constraint ' || bound.conname || ' ' || pg_get_constraintdef(bound.oid)
            FROM relations AS relation
            JOIN pg_constraint AS bound ON bound.conrelid = relation.oid
            UNION ALL
            SELECT relation.relname, 3, named.relname,
                '  index ' || named.relname
                    || CASE WHEN indexed.indisunique THEN ' unique ' ELSE ' ' END
                    || regexp_replace(pg_get_indexdef(indexed.indexrelid), '^.*? USING ', 'using ')
            FROM relations AS relation
            JOIN pg_index AS indexed ON indexed.indrelid = relation.oid
            JOIN pg_class AS named ON named.oid = indexed.indexrelid
            WHERE NOT EXISTS (
                SELECT 1 FROM pg_constraint AS bound
                WHERE bound.conindid = indexed.indexrelid AND bound.contype IN ('p', 'u', 'x'))
        ) AS lines
        ORDER BY relation, part, item
        """;

    // PRIV-RET-003 AC2: every column of the library's schema whose type carries a time
    // of day, with that type, an array read as its element. An instant has a time of
    // day whatever the column is named; a date has none, so it is a calendar day and
    // no instant, and it has no zone to be stored in.
    private const string TimesOfDay =
        """
        SELECT table_name || '.' || column_name || ' ' || ltrim(udt_name, '_')
        FROM information_schema.columns
        WHERE table_schema = 'identity'
            AND ltrim(udt_name, '_') IN ('timestamp', 'timestamptz', 'time', 'timetz')
        ORDER BY table_name, column_name
        """;

    /// <summary>
    /// LIB-API-001 AC2: the library-owned schema is the committed one, so a table,
    /// column, constraint or index that changes fails here until the change is written
    /// into the file beside this test, where it is the reviewable diff.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task LIB_API_001_AC2_TheLibraryOwnedSchemaIsTheContractAsync() =>
        Assert.Equal(
            Repository.ReadText("tests/Janus.Storage.Tests/schema.txt")
                .ReplaceLineEndings("\n")
                .Split('\n', StringSplitOptions.RemoveEmptyEntries),
            await SchemaAsync());

    /// <summary>
    /// LIB-TEST-002 AC2: the ancestry closure is queried from a host's own SQL and
    /// cannot be restructured without a major version, so its structure is stated here
    /// as well as in the committed schema, and a change to it fails both.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task LIB_TEST_002_AC2_TheAncestryClosureStructureIsTheContractAsync()
    {
        IReadOnlyList<string> schema = await SchemaAsync();

        Assert.Equal(
            [
                "table ancestry",
                "  column resource_type text not null",
                "  column resource_id text not null",
                "  column ancestor_type text not null",
                "  column ancestor_id text not null",
                "  column depth integer not null",
                "  column organization uuid not null",
                "  constraint ck_ancestry_depth CHECK ((depth >= 0))",
                "  constraint pk_ancestry PRIMARY KEY (resource_type, resource_id, ancestor_type, ancestor_id)",
                "  index ix_ancestry_ancestor using btree (ancestor_type, ancestor_id)",
            ],
            schema
                .SkipWhile(line => line != "table ancestry")
                .TakeWhile((line, at) => at == 0 || line.StartsWith("  ", StringComparison.Ordinal)));
    }

    /// <summary>
    /// PRIV-RET-003 AC2: every instant the library stores is a <c>timestamp with time
    /// zone</c>, which PostgreSQL keeps in UTC, so no column holds a time of day in a
    /// zone nobody recorded.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task PRIV_RET_003_AC2_EveryStoredInstantIsInUtcAsync()
    {
        await using NpgsqlConnection connection = await database.OpenAsync();

        string[] carried = [.. await connection.QueryAsync<string>(TimesOfDay)];

        Assert.NotEmpty(carried);
        Assert.All(carried, column => Assert.EndsWith(" timestamptz", column, StringComparison.Ordinal));
    }

    /// <summary>
    /// PRIV-RIGHT-005a AC18 (D-174): every column of a library table that can hold a
    /// subject identifier in any row, found from the model and not from a list, refuses
    /// the max UUID in the migrated database: a column typed as a subject, and the
    /// identifier a subject-type discriminator pairs with, which names a subject in some
    /// rows and a group in others. A column added later fails here until it has the check.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task PRIV_RIGHT_005a_AC18_EveryColumnThatCanHoldASubjectRefusesTheMaxUuidAsync()
    {
        IReadOnlyList<(string Table, string Column)> columns = SubjectColumns();

        Assert.Contains(("audit_records", "acting_subject"), columns);
        Assert.Contains(("audit_records", "effective_subject"), columns);
        Assert.Contains(("audit_records", "subject"), columns);
        Assert.Contains(("grants", "subject_id"), columns);
        Assert.Contains(("group_members", "member_id"), columns);
        Assert.Contains(("group_closure", "member_id"), columns);

        await using NpgsqlConnection connection = await database.OpenAsync();

        foreach ((string table, string column) in columns)
        {
            IEnumerable<string> checks = await connection.QueryAsync<string>(
                """
                SELECT pg_get_constraintdef(bound.oid)
                FROM pg_constraint AS bound
                JOIN pg_class AS held ON held.oid = bound.conrelid
                JOIN pg_namespace AS owner ON owner.oid = held.relnamespace
                WHERE owner.nspname = 'identity' AND held.relname = @table AND bound.contype = 'c'
                """,
                new { table });

            Assert.True(
                checks.Contains($"CHECK (({column} <> 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))"),
                $"{table}.{column} does not refuse the max UUID.");
        }
    }

    /// <summary>
    /// PRIV-RIGHT-005a AC18 (D-174): the subject-key table's key and the key rotation's
    /// cursor into it name a row of that table, a subject's or the deployment's, so
    /// neither is typed as a subject and neither refuses the max UUID.
    /// </summary>
    /// <returns>The work of the test.</returns>
    [Fact]
    public async Task PRIV_RIGHT_005a_AC18_TheSubjectKeyTableAndTheRotationCursorNameARowAsync()
    {
        using StoreContext context = new DesignTimeContextFactory().CreateDbContext([]);

        Assert.Equal(
            typeof(SubjectKeyId),
            context.Model.FindEntityType(typeof(SubjectKeyRecord))!.FindPrimaryKey()!.Properties.Single().ClrType);
        Assert.Equal(
            typeof(SubjectKeyId?),
            context.Model.FindEntityType(typeof(KeyRotationRecord))!.FindProperty(nameof(KeyRotationRecord.LastKey))!.ClrType);

        await using NpgsqlConnection connection = await database.OpenAsync();

        Assert.Empty(await connection.QueryAsync<string>(
            """
            SELECT bound.conname
            FROM pg_constraint AS bound
            JOIN pg_class AS held ON held.oid = bound.conrelid
            JOIN pg_namespace AS owner ON owner.oid = held.relnamespace
            WHERE owner.nspname = 'identity'
                AND held.relname IN ('subject_keys', 'key_rotations')
                AND pg_get_constraintdef(bound.oid) LIKE '%ffffffff-ffff-ffff-ffff-ffffffffffff%'
            """));
    }

    // Every column of a mapped table that can hold a subject identifier: one whose type is
    // a subject's, and the identifier beside each subject-type discriminator, which the
    // discriminator's name gives with Id in place of Type.
    private static List<(string Table, string Column)> SubjectColumns()
    {
        using StoreContext context = new DesignTimeContextFactory().CreateDbContext([]);

        List<(string Table, string Column)> columns = [];

        foreach (IEntityType entity in context.Model.GetEntityTypes())
        {
            if (entity.GetTableName() is not string table)
            {
                continue;
            }

            var stored = StoreObjectIdentifier.Table(table, entity.GetSchema());

            foreach (IProperty property in entity.GetProperties())
            {
                Type type = Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType;

                if (type == typeof(SubjectId))
                {
                    columns.Add((table, property.GetColumnName(stored)!));
                }
                else if (type == typeof(SubjectType))
                {
                    string paired = property.Name[..^"Type".Length] + "Id";
                    IProperty identifier = entity.FindProperty(paired)
                        ?? throw new InvalidOperationException($"{table} has a subject type and no {paired} beside it.");

                    columns.Add((table, identifier.GetColumnName(stored)!));
                }
            }
        }

        return columns;
    }

    private async Task<IReadOnlyList<string>> SchemaAsync()
    {
        await using NpgsqlConnection connection = await database.OpenAsync();

        return [.. await connection.QueryAsync<string>(Rendered)];
    }
}
